### ISSUE TITLE
Matomo has CLAWs 🐯

### ISSUE THREAD

**Issue by DonRichards** [Islandora/documentation#1511] opened 2020-05-15 18:36 UTC
In islandora 8 VM go to [http://localhost:8000/matomo/...](http://localhost:8000/matomo/index.php?module=MultiSites&action=index&date=yesterday&period=day&idSite=1)
:tiger:
<img width="1223" alt="Screen Shot 2020-05-15 at 2 32 53 PM" src="https://user-images.githubusercontent.com/2738244/82084298-14c82a80-96b9-11ea-9dd1-2ade490307a3.png">

**Comment by DonRichards** [comment] 2020-05-15 18:38
Should I start calling this 🐯 Tiger ...ING, a play on the Tiger King popularity.

**Comment by bseeger** [comment] 2020-05-18 18:04
Hi @DonRichards  - this is a duplicate of #1482.

**Comment by manez** [comment] 2020-05-20 17:56
Closing duplicate

**Closed as completed by manez** 2020-05-20 17:56 UTC
