### ISSUE TITLE
[BUG] Database update errors out after updating to Drupal 10.3.1 (solution included)

### ISSUE THREAD

**Issue by RodBruce** [Islandora/documentation#2329] opened 2024-07-10 14:17 UTC
**What steps does it take to reproduce the issue?**

1. Run 'composer update'
2. Fix 'composer.json' file to use drupal namespace for specific islandora modules
3. Re-run 'composer update'
4. Run 'drush updb'

* When does this issue occur?
After updating Drupal core to 10.3.1 and executing 'drush updb'
I think this is related to the new index that is added to the locales_location table as mentioned in the Drupal 10.3.1 [release notes](https://www.drupal.org/project/drupal/releases/10.3.1) under "Important changes to this release."

**Solution**
The problem is with the Drupal "Form Mode Control" module. Here is the [bug report](https://www.drupal.org/project/form_mode_control/issues/3431354). The database updates worked after I applied [this patch](https://www.drupal.org/files/issues/2024-06-24/3431354-5.patch).

* Which page does it occur on?
From the command line

* What happens?
There is an AssertionError during 'system_post_update_add_langcode_to_all_translatable_config'

* To whom does it occur (anonymous visitor, editor, administrator)?
SysAdmins

* What did you expect to happen?
A clean database update

**Which version of Islandora are you using?**
2.12.2

**Which method did you use to install your Islandora instance? (manually, ISLE, playbook, etc.)**
Playbook

**Any related open or closed issues to this bug report?**
https://www.drupal.org/project/form_mode_control/issues/3431354

**Screenshots:**
![image](https://github.com/Islandora/documentation/assets/52289790/d3d4677b-c9de-49b7-ab0e-57eda4d9c059)

**Comment by seth-shaw-asu** [comment] 2024-07-10 17:45
Looking over this, it appears that the issue isn't related to islandora specifically, but rather the form_control_module, which we don't include in any of our build tools. So I'm closing this as unrelated to Islandora.

**Closed as not planned by seth-shaw-asu** 2024-07-10 17:45 UTC
Labels: Type: bug

**Comment by RodBruce** [comment] 2024-07-10 18:27
@seth-shaw-asu 
The reason I submitted this as a bug is because when I run `composer why drupal/form_mode_control` I get:
`islandora/islandora-starter-site - requires drupal/form_mode_control (^2.0) `

**Comment by seth-shaw-asu** [comment] 2024-07-10 19:58
*Weird*. I closed it because I searched our repos and the module didn't pop up. It isn't in the [current starter-site composer.json](https://github.com/Islandora-Devops/islandora-starter-site/blob/main/composer.json#L29-L68).

**Comment by seth-shaw-asu** [comment] 2024-07-10 20:04
What I'm thinking is that *after* you built the site you ran `composer require drupal/form_mode_control:^2.0`; but since [the site is still *called* "islandora/islandora-starter-site" in the `composer.json`](https://github.com/Islandora-Devops/islandora-starter-site/blob/main/composer.json#L2), that is why it is blaming it even though it didn't come with it initially.

**Comment by RodBruce** [comment] 2024-07-10 20:09
Seth, you're right. I just checked our additional modules that we install when we build a new instance and we do exactly what you said. Sorry about that.
