### ISSUE TITLE
Bug? hook_media_update(), $parent->save(), generates EmitMediaEvent for a Node

### ISSUE THREAD

**Issue by antbrown** [Islandora/documentation#2069] opened 2022-03-30 09:29 UTC
Steps to reproduce.

1. Implement hook_media_update()
2. Fetch parent node `$islandora = \Drupal::service('islandora.utils'); $parent = $islandora->getParentNode($media);`
3. Make changes to parent node and save: `$parent->save();`
4. Observe the error: "Error generating event: Bundle islandora_object does not exist" (or whatever bundle your parent node is).

Big note: This occurs on #cb52ddd, I need to update to 2.x before confirming it exists there as well, but this will take me a couple of days based on current workload. If anyone is able to do it faster, or knows if EmitEvent/EmitMediaEvent has addressed this issue since then, it would be much appreciated.

Further observations:

* It seems to occur in https://github.com/Islandora/islandora/blob/cb52ddd9021131c25674099b67aa0ae5a2067619/src/Plugin/Action/EmitMediaEvent.php#L107 where the `$entity` is the `$parent` above. Being a `Node` object, it can't find the source field name for the bundle.
* It feels like the Event is being generated based on the entity being saved and the current route, and the type of event is based on the current route alone, not the type of Entity.
* The correct EmitMediaEvent is generated on saving the Media item, but the EmitNodeEvent isn't generated for the `$parent`.

If anyone knows this part of the system and could point me in the right direction, that would be awesome.

Cheers,
Ant

**Comment by jordandukart** [comment] 2022-03-30 17:26
Hey @antbrown did the following and couldn't reproduce:

```php
<?php

use Drupal\media\MediaInterface;

/**
 * Implements hook_media_update().
 */
function mymodule_media_update(MediaInterface $media) {
  $parent = \Drupal::service('islandora.utils')->getParentNode($media);
  $parent->set('title', 'test');
  $parent->save();
}
```
My parent node returned from the utils call gets its title updated. Any further information as to what's triggering / a bigger stacktrace?

My method of testing was:
Create a media, save it.
Go back and update some value that triggers the above hook, save.

**Comment by antbrown** [comment] 2022-03-30 18:13
Hi @jordandukart, thanks for the quick turnaround. I'll try get some more data for you later today. Out of interest, when you tested did you use islandora 2.x or #cb52ddd? Cheers, Ant.

**Comment by jordandukart** [comment] 2022-03-30 18:19
I'm running off of `HEAD` currently, feel free to ping me in Slack as well if you'd like!

**Comment by jordandukart** [comment] 2022-04-07 15:56
Hey @antbrown any progress / updates on this?

**Comment by lucasvanschaik** [comment] 2023-02-14 15:48
Hi @antbrown and @jordandukart,

I got the same error when trying to migrate objects from Islandora 7 to Islandora 8.
After much debugging I noticed that Islandora provides its own ContextManager (Drupal\islandora\IslandoraContextManager) that extends Drupal\context\ContextManager and that the latter has received two bug fixes that the former did not get.
After applying the bug fixes, the error disappears. Apparently some contexts are not evaluated properly resulting in emitting the wrong event(s).

The code changes and issues are described here:
https://git.drupalcode.org/project/context/-/commit/b7e8b7f2295d661dc83513e282df4234c9c390c1
https://git.drupalcode.org/project/context/-/commit/d31cd87b909737abd1beab10e68c62ec29acce35

These changes result in firing less events, but I think only the right events fire now. I will test this change on our development server, but please review and test this as well.

NB: these changes might also solve another bug (that was already solved another way): https://github.com/Islandora/documentation/issues/1848

regards,
Lucas

**Comment by seth-shaw-asu** [comment] 2023-02-15 18:27
@lucasvanschaik, would you be willing to issue a pull request with the specific changes?

**Comment by lucasvanschaik** [comment] 2023-02-17 16:55
I have tested some more and noticed that the above fix did not fully solve the problem. I've dug deeper and found another issue and solution.
Both are in the PR: https://github.com/Islandora/islandora/pull/931

**Comment by jordandukart** [comment] 2023-03-14 12:26
Think we may be able to close this with https://github.com/Islandora/islandora/pull/931 and https://github.com/Islandora/islandora/pull/932 being merged.

**Closed as completed** 2023-03-14 14:56 UTC
